### ISSUE TITLE
Error when will execute lein repl

### ISSUE THREAD

**Issue by Wellers0n** [runopsio/sequence#22]
I'm following this guide, but I'm with a error on line 15
  
https://github.com/runopsio/sequence#developing-sequence

![image](https://user-images.githubusercontent.com/39449389/106504742-1daa9780-64a6-11eb-8325-6665c3cad0fd.png)

**Comment by andriosrobert** [comment]
Great point @Wellers0n! 

I'm updating this, the name of the function is: `start-dev` not `run-dev`

Can you try using `start-dev` instead?

Let me know if it works

**Comment by Wellers0n** [comment]
I think it doesn't work

![image](https://user-images.githubusercontent.com/39449389/106746537-72aef080-6601-11eb-88c3-5a44b79a4fa1.png)

**Comment by andriosrobert** [comment]
yep, it worked! you can use it on localhost:8910 now

**Comment by Wellers0n** [comment]
done
